version: 2.1
executors:
  python37_executor:
    environment:
      TZ: "Asia/Tokyo"
    docker:
      - image: circleci/python:3.7
  python36_executor:
    environment:
      TZ: "Asia/Tokyo"
    docker:
      - image: circleci/python:3.6
  python35_executor:
    environment:
      TZ: "Asia/Tokyo"
    docker:
      - image: circleci/python:3.5
  git_executor:
    environment:
      TZ: "Asia/Tokyo"
    docker:
      - image: alpine/git

commands:
  setup_hub:
    steps:
      - run:
          name: install hub
          command: |
            apk update && apk add --no-cache bash make go groff util-linux
            git clone https://github.com/github/hub
            cd hub
            make install prefix=/usr/local


jobs:
  test_python37:
    executor: python37_executor
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          mv cliboa/template/Pipfile.above37 Pipfile
          pipenv install --dev --skip-lock
    - run:
        name: execute flake8
        command: |
          pipenv run flake8
    - run:
        name: execute unittest and instrument coverage with python3.7
        command: |
          pipenv run coverage

  test_python36:
    executor: python36_executor
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          mv cliboa/template/Pipfile.above36 Pipfile
          pipenv install --dev --skip-lock
    - run:
        name: execute flake8
        command: |
          pipenv run flake8
    - run:
        name: execute unittest and instrument coverage with python3.6
        command: |
          pipenv run coverage

  test_python35:
    executor: python35_executor
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          mv cliboa/template/Pipfile.above35 Pipfile
          pipenv install --dev --skip-lock
    - run:
        name: execute flake8
        command: |
          pipenv run flake8
    - run:
        name: execute unittest and instrument coverage with python3.5
        command: |
          pipenv run coverage

  push_dev_branch: # push development branch to GitHub
    executor: git_executor
    steps:
      - checkout
      - setup_hub
      - add_ssh_keys:
          fingerprints:
            - "b3:b1:fb:ac:f6:45:cf:83:ef:bc:8b:a8:c3:2a:20:51"
      - run:
          name: push development branch to GitHub
          command: |
            cd cliboa
            git checkout development
            git remote add upstream git@github.com:BrainPad/cliboa.git
            git push upstream development -f
            hub request-pull -m "development->master" -b master

rollout_filter: &rollout_filter
  filters:
    branches:
      only:
        - "92"
        # - development
  
workflows:
  test_all_support_python_ver:
    jobs:
      - test_python37
      - test_python36
      - test_python35
      - push_dev_branch:
          <<: *rollout_filter
          #requires:
          #  - test_python37
          #  - test_python36
          #  - test_python35
