name: cliboa-stale

on:
  schedule:
    - cron: '30 0 1 * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Mark stale issues and pull requests
        uses: actions/stale@v9
        with:
          days-before-stale: 365
          days-before-close: -1
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It may be closed if no further activity occurs. Thank you for your contributions.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It may be closed if no further activity occurs. Thank you for your contributions.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'no-stale'
          exempt-issue-labels: 'no-stale'
          operations-per-run: 100
