name: cliboa-test-functional

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
  schedule:
    - cron: '10 0 1 * *'
  workflow_dispatch:

jobs:
  test_by_multiple_python_versions:
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: validate poetry
        run: |
          poetry check --strict

      - name: execute unittest and instrument coverage
        run: |
          poetry run pytest --cov cliboa --cov-report term-missing --cov-report=xml
