name: cliboa-deploy

on:
  push:
    branches:
      - "224" # debug
  workflow_dispatch:
    inputs:
      token:
        description: PyPI token
        required: true
        default: "spam"

jobs:
  deploy_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          sudo python3 -m pip install twine
      - name: create pypi package
        run: |
          # create package
          sudo python3 setup.py sdist bdist_wheel
      - name: upload to pypi
        run: |
          # fetch a pypi token
          PYPI_TOKEN=`jq -r '.inputs.token' $GITHUB_EVENT_PATH`
          echo ::add-mask::$PYPI_TOKEN
          # upload a python package to pypi
          sudo python3 -m twine upload --repository pypi dist/* -u "__token__" -p $PYPI_TOKEN